import { chromium } from '@playwright/test';
const [url, out, frame, opacity] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
await page.goto(url); await page.waitForTimeout(3500);
await page.evaluate(([f, o]) => { const s = window.__meraStore; s.getState().set({ photo: { frameId: f, aligned: true, opacity: Number(o) } }); }, [frame, opacity]);
await page.waitForTimeout(2500);
await page.screenshot({ path: out });
console.log(errs);
await browser.close();
